### ISSUE TITLE
System.StackOverflowExecption Errors. 

### ISSUE THREAD

**Issue by Keratin-dev** [ToshiroZ/Courvix-VPN#1]
### System.StackOverflowExecption Errors.
 Basically there's an error that this project gets that gives a System.StackOverflowExecption every time you attempt to make a http request.
 to fix it just do the following

- remove Newtonsoft.json reference from the project
- go to https://www.newtonsoft.com/json and download the zip file with the DLL
- then add it to the reference folder (make sure its 13.0.1) 

- if there are still errors then go to `packages.config` and completely remove the line with Newtonsoft.json as a package from it

then the problems should be fixed and you can make http requests to the Courvix json page no problems.

**this is just a recommendation to be fixed but follow the above and its fine.**

**Comment by ToshiroZ** [comment]
That is not an exception that is ever thrown. I am using newtonsoft 13.0.1 from nuget
